version: '3.8'
services:
  mysql-graphql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=graphql
      - MYSQL_DATABASE=graphql
      - MYSQL_USER=graphql
      - MYSQL_PASSWORD=graphql