version: '3.8'
services:
  mysql-graphql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=graphql
      - MYSQL_DATABASE=graphql
      - MYSQL_USER=graphql
      - MYSQL_PASSWORD=graphql
  redis-gql-subpub:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass gql-subpub
    volumes:
      - cache:/data
  mongodb-auth:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=auth-graphql
      - MONGO_INITDB_ROOT_PASSWORD=auth-graphql
      - MONGO_INITDB_DATABASE=auth-graphql
volumes:
  cache:
    driver: local